import { createSlice } from '@reduxjs/toolkit';

// Initial state for the slice
const initialState = {
  allProductData: [],
};

// Create a slice using createSlice
const allProductDataSlice = createSlice({
  name: 'allProductData', // Name of the slice
  initialState, // Initial state
  reducers: {
    // Reducer function to set products
    setProducts: (state, action) => {
      state.allProductData = action.payload.data;
    },
    // Reducer function to remove products
    removeProducts: (state) => {
      state.allProductData = [];
      console.log("removed");
    },
  },
});

// Export actions generated by createSlice
export const { setProducts, removeProducts } = allProductDataSlice.actions;

// Export the reducer generated by createSlice
export default allProductDataSlice.reducer;
